# Makefile for Orion-X4 userspace programs
# Written in 2013



CXX		= ../../build/toolchain/bin/x86_64-orionx-g++
AS		= ../../build/toolchain/bin/x86_64-orionx-as
LD		= ../../build/toolchain/bin/x86_64-orionx-ld


CXXFLAGS	= -Wall -s -Os -std=gnu++11 -I../../build/sysroot/usr/include/freetype2

CXXOBJ	= $(CXXSRC:.c=.o)
CXXOPT	= /Volumes/mx/hello


.PHONY: all

all:
	@:

