#ifndef RDESTL_ALLOCATOR_H
#define RDESTL_ALLOCATOR_H

#include "rdestl_common.h"

namespace rde
{

// CONCEPT!
class allocator
{
public:
	explicit allocator(const char* name = "DEFAULT"):	m_name(name) {}
	explicit allocator(const allocator& other): m_name(other.m_name) {}
	// Copy ctor generated by compiler.
	// allocator(const allocator&)
	~allocator() {}

	// Generated by compiler.
	//allocator& operator=(const allocator&)

	void* allocate(size_t bytes, int flags = 0);
	// Not supported for standard allocator for the time being.
	void* allocate_aligned(size_t bytes, size_t alignment, int flags = 0);
	void deallocate(void* ptr, size_t bytes);

	const char* get_name() const;

private:
	const char*	m_name;
};

// True if lhs can free memory allocated by rhs and vice-versa.
inline bool operator==(const allocator& /*lhs*/, const allocator& /*rhs*/)
{
	return true;
}
inline bool operator!=(const allocator& lhs, const allocator& rhs)
{
	return !(lhs == rhs);
}

inline void* allocator::allocate(size_t bytes, int)
{
	return malloc(bytes);
	// return operator new(bytes);
}

inline void allocator::deallocate(void* ptr, size_t)
{
	// operator delete(ptr);
	free(ptr);
}

} // namespace rde

//-----------------------------------------------------------------------------
#endif // #ifndef RDESTL_ALLOCATOR_H
